spring:
    application:
        name: bns
    thymeleaf:
        check-template-location: false
    datasource:
        url: jdbc:postgresql://dpg-csda98jqf0us73b2dp6g-a.oregon-postgres.render.com/hotel_management_system_904b
        username: hotel_management_system_904b_user
        password: vvbFhOyIoBRtcKK3t769JrF8thYZTRB9
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: ${PORT}
    servlet:
        context-path: /api/v1/
    tomcat:
        accesslog:
            enabled: true

application:
    security:
        jwt:
            secret-key: d3ffcbd71addcf431293a511dd158251467304adce59ea13ddfc2c39468016ad
            expiration: 360000000