spring:
    application:
        name: bns
    thymeleaf:
        check-template-location: false
    datasource:
        url: jdbc:postgresql://hotel_management_system_904b_user:vvbFhOyIoBRtcKK3t769JrF8thYZTRB9@dpg-csda98jqf0us73b2dp6g-a/hotel_management_system_904b
        username: hotel_management_system_904b_user
        password: vvbFhOyIoBRtcKK3t769JrF8thYZTRB9
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8001
    servlet:
        context-path: /api/v1/

application:
    security:
        jwt:
            secret-key: d3ffcbd71addcf431293a511dd158251467304adce59ea13ddfc2c39468016ad
            expiration: 360000000